Document: npm-aliases
Title: Debian npm-aliases Manual
Author: <insert document author here>
Abstract: This manual describes what npm-aliases is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/npm-aliases/npm-aliases.sgml.gz

Format: postscript
Files: /usr/share/doc/npm-aliases/npm-aliases.ps.gz

Format: text
Files: /usr/share/doc/npm-aliases/npm-aliases.text.gz

Format: HTML
Index: /usr/share/doc/npm-aliases/html/index.html
Files: /usr/share/doc/npm-aliases/html/*.html
